import { Head, Link } from '@inertiajs/react';

function Logo({ className = 'h-8 w-8' }) {
    return (
        <svg
            viewBox="0 0 32 32"
            xmlns="http://www.w3.org/2000/svg"
            className={className}
            aria-hidden="true"
        >
            <defs>
                <linearGradient id="logo-g" x1="0" x2="1" y1="0" y2="1">
                    <stop offset="0%" stopColor="#6366f1" />
                    <stop offset="100%" stopColor="#06b6d4" />
                </linearGradient>
            </defs>
            <circle cx="16" cy="16" r="4" fill="url(#logo-g)" />
            <circle cx="5" cy="6" r="2.5" fill="url(#logo-g)" opacity="0.9" />
            <circle cx="27" cy="6" r="2.5" fill="url(#logo-g)" opacity="0.9" />
            <circle cx="27" cy="26" r="2.5" fill="url(#logo-g)" opacity="0.9" />
            <circle cx="5" cy="26" r="2.5" fill="url(#logo-g)" opacity="0.9" />
            <circle cx="16" cy="2.5" r="1.8" fill="url(#logo-g)" opacity="0.7" />
            <path
                d="M16 16 L5 6 M16 16 L27 6 M16 16 L27 26 M16 16 L5 26 M16 16 L16 2.5"
                stroke="url(#logo-g)"
                strokeWidth="1.2"
                opacity="0.5"
                fill="none"
            />
        </svg>
    );
}

const features = [
    {
        title: '5 subtopics per keyword',
        description:
            'Pick a topic and we return 5 semantically related subtopics with their own long-tail keyword.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <path
                    d="M12 3v18M3 12h18"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                />
            </svg>
        ),
    },
    {
        title: '10 user-intent questions',
        description:
            'For each subtopic, 10 real questions your audience is actually searching for.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <path
                    d="M9.5 9a2.5 2.5 0 1 1 3.5 2.3c-.8.3-1.5 1-1.5 1.9V14M12 17h.01"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                />
                <circle
                    cx="12"
                    cy="12"
                    r="9"
                    stroke="currentColor"
                    strokeWidth="2"
                />
            </svg>
        ),
    },
    {
        title: 'AI-written answers',
        description:
            'Each question gets a concise, SEO-friendly answer generated by Google Gemini.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <path
                    d="M4 4h16v12H5.5L4 18V4z"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinejoin="round"
                />
                <path
                    d="M8 9h8M8 13h5"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                />
            </svg>
        ),
    },
    {
        title: '1 pillar + 5 cluster pages',
        description:
            'We assemble a pillar page for your main keyword and a cluster page for every subtopic.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <path
                    d="M4 6h16M4 12h10M4 18h16"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                />
            </svg>
        ),
    },
    {
        title: 'Export markdown',
        description:
            'Download every page as a clean .md file ready for your CMS or static site.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <path
                    d="M12 4v12m0 0-4-4m4 4 4-4M5 20h14"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                />
            </svg>
        ),
    },
    {
        title: 'Live status polling',
        description:
            'Watch the progress bar tick through each step — queued, subtopics, questions, answers, pages.',
        icon: (
            <svg viewBox="0 0 24 24" fill="none" className="h-6 w-6">
                <circle
                    cx="12"
                    cy="12"
                    r="9"
                    stroke="currentColor"
                    strokeWidth="2"
                />
                <path
                    d="M12 7v5l3 2"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                />
            </svg>
        ),
    },
];

const steps = [
    {
        num: '01',
        title: 'Enter topic + website',
        body: 'Paste your main keyword and the site you want to rank.',
    },
    {
        num: '02',
        title: 'Gemini generates subtopics',
        body: '5 long-tail subtopics derived from your target keyword.',
    },
    {
        num: '03',
        title: 'Questions + answers',
        body: '10 questions per subtopic, each with an AI-written answer.',
    },
    {
        num: '04',
        title: 'Pillar + cluster pages',
        body: 'One pillar page and 5 cluster pages — ready to publish.',
    },
];

export default function Welcome({ auth }) {
    return (
        <>
            <Head title="ClusterForge — AI Keyword Clusters for SEO" />
            <div className="relative min-h-screen overflow-hidden bg-slate-950 text-slate-100">
                {/* Decorative background */}
                <div className="pointer-events-none absolute inset-0 -z-10">
                    <div className="absolute left-1/2 top-[-10rem] h-[32rem] w-[56rem] -translate-x-1/2 rounded-full bg-indigo-500/25 blur-[120px]" />
                    <div className="absolute right-[-6rem] top-[18rem] h-80 w-80 rounded-full bg-cyan-400/20 blur-[100px]" />
                    <div className="absolute left-[-6rem] top-[30rem] h-80 w-80 rounded-full bg-fuchsia-500/15 blur-[100px]" />
                    <div
                        className="absolute inset-0 opacity-[0.05]"
                        style={{
                            backgroundImage:
                                'linear-gradient(rgba(255,255,255,.5) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.5) 1px, transparent 1px)',
                            backgroundSize: '44px 44px',
                        }}
                    />
                </div>

                {/* Nav */}
                <header className="relative z-10">
                    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6">
                        <Link
                            href="/"
                            className="flex items-center gap-2 text-lg font-semibold"
                        >
                            <Logo className="h-8 w-8" />
                            <span>ClusterForge</span>
                        </Link>
                        <div className="hidden items-center gap-8 text-sm text-slate-300 md:flex">
                            <a
                                href="#features"
                                className="hover:text-white"
                            >
                                Features
                            </a>
                            <a href="#how" className="hover:text-white">
                                How it works
                            </a>
                            <a
                                href="#faq"
                                className="hover:text-white"
                            >
                                FAQ
                            </a>
                        </div>
                        <div className="flex items-center gap-3">
                            {auth?.user ? (
                                <Link
                                    href={route('dashboard')}
                                    className="rounded-full bg-white px-4 py-2 text-sm font-medium text-slate-900 transition hover:bg-slate-200"
                                >
                                    Dashboard
                                </Link>
                            ) : (
                                <>
                                    <Link
                                        href={route('login')}
                                        className="rounded-full px-4 py-2 text-sm font-medium text-slate-200 transition hover:text-white"
                                    >
                                        Log in
                                    </Link>
                                    <Link
                                        href={route('register')}
                                        className="rounded-full bg-gradient-to-r from-indigo-500 to-cyan-400 px-4 py-2 text-sm font-semibold text-slate-900 shadow-lg shadow-indigo-500/20 transition hover:from-indigo-400 hover:to-cyan-300"
                                    >
                                        Get started
                                    </Link>
                                </>
                            )}
                        </div>
                    </nav>
                </header>

                {/* Hero */}
                <section className="relative z-10 mx-auto max-w-7xl px-6 pb-24 pt-16 lg:pt-24">
                    <div className="mx-auto max-w-3xl text-center">
                        <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-300 backdrop-blur">
                            <span className="relative flex h-2 w-2">
                                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
                                <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" />
                            </span>
                            Powered by Google Gemini
                        </span>
                        <h1 className="mt-6 text-4xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-6xl">
                            Turn one keyword into a{' '}
                            <span className="bg-gradient-to-r from-indigo-400 via-sky-300 to-cyan-300 bg-clip-text text-transparent">
                                full SEO topic cluster
                            </span>{' '}
                            in minutes.
                        </h1>
                        <p className="mt-6 text-lg text-slate-300 sm:text-xl">
                            Enter a topic and your website. Get 5 subtopics, 50
                            user-intent questions, AI answers, and a ready-to-publish
                            pillar + 5 cluster pages.
                        </p>
                        <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
                            <Link
                                href={
                                    auth?.user
                                        ? route('projects.create')
                                        : route('register')
                                }
                                className="group inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-indigo-500 to-cyan-400 px-6 py-3 text-base font-semibold text-slate-900 shadow-xl shadow-indigo-500/30 transition hover:from-indigo-400 hover:to-cyan-300"
                            >
                                {auth?.user
                                    ? 'Create a project'
                                    : 'Start free — no credit card'}
                                <svg
                                    viewBox="0 0 20 20"
                                    fill="currentColor"
                                    className="h-4 w-4 transition group-hover:translate-x-1"
                                >
                                    <path
                                        fillRule="evenodd"
                                        d="M3 10a.75.75 0 01.75-.75h10.638L10.23 5.29a.75.75 0 111.04-1.08l5.5 5.25a.75.75 0 010 1.08l-5.5 5.25a.75.75 0 11-1.04-1.08l4.158-3.96H3.75A.75.75 0 013 10z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                            </Link>
                            <a
                                href="#how"
                                className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3 text-base font-medium text-slate-200 backdrop-blur transition hover:bg-white/10"
                            >
                                See how it works
                            </a>
                        </div>
                    </div>

                    {/* Preview card */}
                    <div className="relative mx-auto mt-16 max-w-5xl">
                        <div className="absolute -inset-1 rounded-3xl bg-gradient-to-r from-indigo-500/40 via-sky-400/30 to-cyan-400/40 opacity-60 blur-2xl" />
                        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/80 shadow-2xl shadow-indigo-950/40 backdrop-blur">
                            <div className="flex items-center gap-2 border-b border-white/10 bg-slate-950/60 px-4 py-2">
                                <span className="h-3 w-3 rounded-full bg-rose-500/80" />
                                <span className="h-3 w-3 rounded-full bg-amber-400/80" />
                                <span className="h-3 w-3 rounded-full bg-emerald-500/80" />
                                <span className="ml-3 text-xs text-slate-400">
                                    clusterforge.app / projects / local-seo
                                </span>
                            </div>
                            <div className="grid gap-6 p-6 md:grid-cols-5">
                                <div className="md:col-span-2">
                                    <div className="text-xs font-semibold uppercase tracking-wider text-indigo-300">
                                        Pillar page
                                    </div>
                                    <h3 className="mt-2 text-xl font-semibold text-white">
                                        The Complete Guide to Local SEO
                                    </h3>
                                    <p className="mt-2 text-sm text-slate-400">
                                        Long-tail keyword: <span className="text-slate-200">local seo for small business</span>
                                    </p>
                                    <div className="mt-4 space-y-2">
                                        <div className="h-2 w-full rounded bg-slate-700/50" />
                                        <div className="h-2 w-5/6 rounded bg-slate-700/50" />
                                        <div className="h-2 w-4/6 rounded bg-slate-700/50" />
                                    </div>
                                    <div className="mt-4 inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-300">
                                        <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                                        Completed
                                    </div>
                                </div>
                                <div className="md:col-span-3">
                                    <div className="mb-3 text-xs font-semibold uppercase tracking-wider text-cyan-300">
                                        5 cluster pages
                                    </div>
                                    <ul className="space-y-2">
                                        {[
                                            'Google Business Profile checklist',
                                            'Local citation building strategy',
                                            'On-page SEO for local landing pages',
                                            'Getting reviews that drive rankings',
                                            'Local link building tactics',
                                        ].map((t) => (
                                            <li
                                                key={t}
                                                className="flex items-center justify-between rounded-lg border border-white/5 bg-white/5 px-3 py-2 text-sm"
                                            >
                                                <span className="text-slate-200">
                                                    {t}
                                                </span>
                                                <span className="text-xs text-slate-400">
                                                    10 Q&amp;A
                                                </span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Features */}
                <section
                    id="features"
                    className="relative z-10 mx-auto max-w-7xl px-6 py-20"
                >
                    <div className="mx-auto max-w-2xl text-center">
                        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                            Everything you need to ship a topic cluster
                        </h2>
                        <p className="mt-4 text-slate-400">
                            Built for SEO teams, solo bloggers, and agencies who
                            want to stop staring at a blank page.
                        </p>
                    </div>
                    <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                        {features.map((f) => (
                            <div
                                key={f.title}
                                className="group rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-white/20 hover:bg-white/[0.06]"
                            >
                                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500/20 to-cyan-400/20 text-cyan-300">
                                    {f.icon}
                                </div>
                                <h3 className="mt-4 text-lg font-semibold text-white">
                                    {f.title}
                                </h3>
                                <p className="mt-2 text-sm text-slate-400">
                                    {f.description}
                                </p>
                            </div>
                        ))}
                    </div>
                </section>

                {/* How it works */}
                <section
                    id="how"
                    className="relative z-10 mx-auto max-w-7xl px-6 py-20"
                >
                    <div className="mx-auto max-w-2xl text-center">
                        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                            How it works
                        </h2>
                        <p className="mt-4 text-slate-400">
                            From blank page to publish-ready cluster in four steps.
                        </p>
                    </div>
                    <div className="relative mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
                        {steps.map((s) => (
                            <div
                                key={s.num}
                                className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"
                            >
                                <div className="text-sm font-semibold text-cyan-300">
                                    {s.num}
                                </div>
                                <h3 className="mt-2 text-lg font-semibold text-white">
                                    {s.title}
                                </h3>
                                <p className="mt-2 text-sm text-slate-400">
                                    {s.body}
                                </p>
                            </div>
                        ))}
                    </div>
                </section>

                {/* FAQ */}
                <section
                    id="faq"
                    className="relative z-10 mx-auto max-w-4xl px-6 py-20"
                >
                    <div className="mx-auto max-w-2xl text-center">
                        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                            Frequently asked
                        </h2>
                    </div>
                    <div className="mt-10 space-y-4">
                        {[
                            {
                                q: 'Which AI model do you use?',
                                a: 'Google Gemini (configurable — defaults to gemini-flash-latest). Bring your own API key from Google AI Studio.',
                            },
                            {
                                q: 'Can I edit the generated content?',
                                a: 'Yes — every page is stored as markdown. Download the .md file or copy from the preview view and edit in your CMS.',
                            },
                            {
                                q: 'How long does generation take?',
                                a: 'Typically 1–3 minutes per project. The progress bar updates live as each step completes.',
                            },
                            {
                                q: 'Do I need a credit card to try it?',
                                a: 'No. Sign up with email, add your Gemini key in your environment, and create your first project.',
                            },
                        ].map((item) => (
                            <details
                                key={item.q}
                                className="group rounded-xl border border-white/10 bg-white/[0.03] p-5 open:bg-white/[0.06]"
                            >
                                <summary className="flex cursor-pointer list-none items-center justify-between text-base font-medium text-white">
                                    {item.q}
                                    <svg
                                        viewBox="0 0 20 20"
                                        fill="currentColor"
                                        className="h-5 w-5 text-slate-400 transition group-open:rotate-180"
                                    >
                                        <path
                                            fillRule="evenodd"
                                            d="M5.23 7.21a.75.75 0 011.06.02L10 11.06l3.71-3.83a.75.75 0 111.08 1.04l-4.25 4.39a.75.75 0 01-1.08 0L5.21 8.27a.75.75 0 01.02-1.06z"
                                            clipRule="evenodd"
                                        />
                                    </svg>
                                </summary>
                                <p className="mt-3 text-sm text-slate-400">
                                    {item.a}
                                </p>
                            </details>
                        ))}
                    </div>
                </section>

                {/* CTA */}
                <section className="relative z-10 mx-auto max-w-5xl px-6 pb-24">
                    <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-indigo-600/30 via-slate-900 to-cyan-500/20 p-10 text-center sm:p-14">
                        <div className="pointer-events-none absolute -left-24 -top-24 h-64 w-64 rounded-full bg-indigo-500/30 blur-3xl" />
                        <div className="pointer-events-none absolute -bottom-24 -right-24 h-64 w-64 rounded-full bg-cyan-400/30 blur-3xl" />
                        <h2 className="relative text-3xl font-bold tracking-tight sm:text-4xl">
                            Ready to build your first cluster?
                        </h2>
                        <p className="relative mt-4 text-slate-300">
                            One topic in. Pillar + 5 cluster pages out. It's that
                            simple.
                        </p>
                        <div className="relative mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
                            <Link
                                href={
                                    auth?.user
                                        ? route('projects.create')
                                        : route('register')
                                }
                                className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-base font-semibold text-slate-900 transition hover:bg-slate-200"
                            >
                                {auth?.user
                                    ? 'New project'
                                    : 'Create a free account'}
                            </Link>
                            {!auth?.user && (
                                <Link
                                    href={route('login')}
                                    className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3 text-base font-medium text-slate-200 transition hover:bg-white/10"
                                >
                                    I already have an account
                                </Link>
                            )}
                        </div>
                    </div>
                </section>

                {/* Footer */}
                <footer className="relative z-10 border-t border-white/5">
                    <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-6 py-8 text-sm text-slate-400 sm:flex-row">
                        <div className="flex items-center gap-2">
                            <Logo className="h-6 w-6" />
                            <span>ClusterForge</span>
                        </div>
                        <div>
                            Built with Laravel, React &amp; Google Gemini.
                        </div>
                    </div>
                </footer>
            </div>
        </>
    );
}
